module.exports = [
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt',
    },
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi', 'Trần Phạm Nguyễn Lê'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 0,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 2,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },

    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },

    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },

    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },
    {
        class: 'Toán cô Chi',
        lessonName: 'Buổi 1 - Hàm số',
        lessonId: '62affdfa263eda6c5680cc0b',
        teacher: ['Diệp Linh Chi'],
        startTime: '01/07/2022 20:30',
        startNote: '01/07/2022 20:30',
        status: 1,
        content: 'Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất Hôm nay các con học tập rất tốt, lớp học đã học về các phương pháp ở phần nghe listening, lớp học rất',
    },

]