module.exports = [
    {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    }, {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    }, {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    }, {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    }, {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    }, {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    }, {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    }, {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    }, {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    }, {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    }, {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    }, {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    }, {
        name: 'IELTS167',
        code: 'IELTS167',
        teacher: ['Trần Thanh Tùng', 'Diệp Linh Chi', 'Diệp Linh Chi'],
        subject: 'IELTS',
        class: 'Hỗn hợp',
        countStudent: 38,
        status: 'online',
    },
]